#!/bin/bash
cd /home/ec2-user/

# install dotnet core
# https://www.microsoft.com/net/core#linuxubuntu
if [ ! -f /usr/bin/dotnet ]; then
    yum install libunwind libicu
    
    curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=835019

    mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
    ln -s /opt/dotnet/dotnet /usr/local/bin
fi

# first time running dotnet tool requires setting up package cache
dotnet nuget
