#!/bin/bash

# install apache if not already installed
yum install httpd -y


# override the existing site configuration
HTTPD_CONF=/etc/httpd/conf/httpd.conf
cp /home/ec2-user/aspnetcoreapp/virtualhost.conf $HTTPD_CONF
