#!/bin/bash
cd /home/ec2-user/

# start apache
service httpd restart

SERVICE_ROOT=/home/ec2-user/aspnetcoreapp
PID_FILE=$SERVICE_ROOT/service.pid

# shut down sevice if it is running already
if [! -f $PID_FILE]; then
    cat $PID_FILE | xargs kill -9
    rm $PID_FILE
fi

# un asp.core application
cd $SERVICE_ROOT
dotnet MvcMovie.dll &>$SERVICE_ROOT/service.log &
echo $! > $SERVICE_ROOT/service.pid
