#!/bin/bash

# stop apache
service httpd stop

# stop dotnet application
SERVICE_ROOT=/home/ec2-user/aspnetcoreapp
PID_FILE=$SERVICE_ROOT/service.pid

if [ -f $PID_FILE ]; then
    cat $PID_FILE | xargs kill -9
    rm $PID_FILE
fi
